sudo: required # super user permissions to execute the build
language: generic
# tell Travis we need a copy of docker running
services:
  - docker

# build our image usinf the Dockerfile.dev
before_install:
  - docker build -t sbhasale/docker-react -f Dockerfile.dev .

# tell Travis how to deploy our code
script:
  - docker run -e CI=true sbhasale/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk # tell travis what set of instructions to use
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-067331374402" # S3 bucket
  bucket_path: "docker-react" # same as app name
  on:
    branch: master # only deploy when code is pushed to master branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY